# Generated by Django 5.0.1 on 2024-01-20 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to=settings.AUTH_USER_MODEL, verbose_name='suit'),
        ),
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
